module.exports = {
    SESSION_KEY_COOKIE_NAME: 'HORIZONPWRSESSION',

    CEO_ROLE                        : 'CEO_ROLE',
    VP_ROLE                         : 'VP_ROLE',
    SALES_SUPPORT_ROLE              : 'SALES_SUPPORT_ROLE',
    ADMIN_ROLE                      : 'ADMIN_ROLE',
    MANAGER_ROLE                    : 'MANAGER_ROLE',
    REGIONAL_MANAGER_ROLE           : 'REGIONAL_MANAGER_ROLE',
    FIELD_MARKETER_ROLE             : 'FIELD_MARKETER_ROLE',
    FIELD_MARKETER_ELITE_ROLE       : 'FIELD_MARKETER_ELITE_ROLE',
    JUNIOR_ENERGY_CONSULTANT_ROLE   : 'JUNIOR_ENERGY_CONSULTANT_ROLE',
    SENIOR_ENERGY_CONSULTANT_ROLE   : 'SENIOR_ENERGY_CONSULTANT_ROLE',
}
